[tool.poetry]
name = "util-py"
version = "0.1.0"
description = ""
authors = ["zweix123 <1979803044@qq.com>"]
readme = "README.md"
packages = [{include = "util_py"}]

[tool.poetry.dependencies]
python = "^3.10"
prettytable = "^3.6.0"
aiohttp = "^3.8.4"
requests = "^2.28.2"
fake-useragent = "^1.1.3"
markdown = "^3.4.3"
chardet = "^5.1.0"
bs4 = "^0.0.1"
tqdm = "^4.65.0"
pypdf2 = "^3.0.1"
numpy = "^1.24.2"
matplotlib = "^3.7.1"
opencv-python = "^4.7.0.72"


[tool.poetry.group.dev.dependencies]
black = "^23.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
